---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: fitness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:8
          ports:
            - containerPort: 27017

          readinessProbe:
            exec:
              command:
                - mongosh
                - --quiet
                - --eval
                - db.adminCommand('ping').ok
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          livenessProbe:
            exec:
              command:
                - mongosh
                - --quiet
                - --eval
                - db.adminCommand('ping').ok
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5

          volumeMounts:
            - name: mongo-data
              mountPath: /data/db

      volumes:
        - name: mongo-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: fitness
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017