---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: fitness
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: fitness-user-db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: root

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U postgres -d fitness-user-db
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U postgres -d fitness-user-db
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 5

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-data
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: fitness
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
